import type { Company, UseCase, Cohort, Track, Quadrant, ValueTheme, InvestmentGroup, PlatformClassification } from './types'
import {
  calculateValueScore,
  calculateReadinessScore,
  calculateAdjustedEbitda,
  calculatePriorityScore,
  calculatePeNativeScore,
  calculatePortfolioAdjustedPriority,
  determineQuadrant,
  determinePlatformClassification,
} from './calculations'

// ============================================================================
// Portfolio Company Data (from Excel workbook)
// ============================================================================

export const PORTFOLIO_DATA: Company[] = [
  // The complete 54 company dataset
  { rank: 1, name: 'Scan Global Logistics', cohort: 'Logistics', investmentGroup: 'Small Business', revenue: 2300, ebitda: 276, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 8, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 7, timelineFit: 8, valueScore: 8, readinessScore: 7.88, priorityScore: 219.18 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 10, replicationCount: 5, adjustedPriority: 59.05, adjustedEbitda: 47.31, peNativeScore: 7.88, portfolioAdjustedPriority: 88.58 },
  { rank: 2, name: 'TricorBraun', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 3000, ebitda: 300, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 6, timelineFit: 7, valueScore: 7.5, readinessScore: 6.85, priorityScore: 215.25 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 17, adjustedPriority: 69.32, adjustedEbitda: 48.21, peNativeScore: 7.12, portfolioAdjustedPriority: 187.18 },
  { rank: 3, name: 'NES Fircroft', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 1500, ebitda: 225, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 7, timelineFit: 7, valueScore: 7, readinessScore: 7, priorityScore: 157.5 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 14, adjustedPriority: 35.36, adjustedEbitda: 33.75, peNativeScore: 7, portfolioAdjustedPriority: 84.86 },
  { rank: 4, name: 'Redwood Logistics', cohort: 'Logistics', investmentGroup: 'Middle Market', revenue: 1000, ebitda: 120, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 8, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 8, timelineFit: 7, valueScore: 8, readinessScore: 7.9, priorityScore: 95.4 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 10, replicationCount: 5, adjustedPriority: 19.54, adjustedEbitda: 20.57, peNativeScore: 7.9, portfolioAdjustedPriority: 29.31 },
  { rank: 5, name: 'Polygon Group', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 900, ebitda: 135, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 7, timelineFit: 7, valueScore: 6.75, readinessScore: 6.25, priorityScore: 87.75 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 8, replicationCount: 14, adjustedPriority: 17.08, adjustedEbitda: 19.46, peNativeScore: 6.38, portfolioAdjustedPriority: 40.98 },
  { rank: 6, name: 'American Oncology Network', cohort: 'Healthcare', investmentGroup: 'Elevate', revenue: 1000, ebitda: 100, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 7, timelineFit: 7, valueScore: 7.5, readinessScore: 7, priorityScore: 72.5 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 7, replicationCount: 7, adjustedPriority: 15.54, adjustedEbitda: 16.07, peNativeScore: 7.17, portfolioAdjustedPriority: 26.41 },
  { rank: 7, name: 'Excelitas Technologies', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 1000, ebitda: 100, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 8, dataReadiness: 7, techInfrastructure: 7, timelineFit: 7, valueScore: 7.5, readinessScore: 7.45, priorityScore: 74.75 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 17, adjustedPriority: 16.00, adjustedEbitda: 16.07, peNativeScore: 7.4, portfolioAdjustedPriority: 43.19 },
  { rank: 8, name: 'BMS Enterprises', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 500, ebitda: 75, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.75, readinessScore: 6.1, priorityScore: 48.19 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 8, replicationCount: 14, adjustedPriority: 9.26, adjustedEbitda: 10.85, peNativeScore: 6.38, portfolioAdjustedPriority: 22.22 },
  { rank: 9, name: 'SitelogIQ', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 430, ebitda: 64.5, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 8, timelineFit: 7, valueScore: 7.5, readinessScore: 7.15, priorityScore: 47.27 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 7, replicationCount: 14, adjustedPriority: 9.97, adjustedEbitda: 10.38, peNativeScore: 7.25, portfolioAdjustedPriority: 23.93 },
  { rank: 10, name: 'Traeger Pellet Grills', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 800, ebitda: 64, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 6, timelineFit: 7, valueScore: 7, readinessScore: 6.85, priorityScore: 44.38 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 7, replicationCount: 11, adjustedPriority: 9.43, adjustedEbitda: 9.6, peNativeScore: 6.88, portfolioAdjustedPriority: 19.80 },
  { rank: 11, name: 'Numotion', cohort: 'Healthcare', investmentGroup: 'Middle Market', revenue: 600, ebitda: 60, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 7, dataReadiness: 6, techInfrastructure: 7, timelineFit: 7, valueScore: 6.75, readinessScore: 6.6, priorityScore: 40.05 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 7, replicationCount: 7, adjustedPriority: 7.74, adjustedEbitda: 8.68, peNativeScore: 6.62, portfolioAdjustedPriority: 13.16 },
  { rank: 12, name: 'Visual Comfort', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 750, ebitda: 60, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 6, timelineFit: 7, valueScore: 7, readinessScore: 6.85, priorityScore: 41.55 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 7, replicationCount: 11, adjustedPriority: 8.74, adjustedEbitda: 9, peNativeScore: 6.88, portfolioAdjustedPriority: 18.35 },
  { rank: 13, name: 'Huge', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 300, ebitda: 45, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 8, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 8, timelineFit: 8, valueScore: 8, readinessScore: 8, priorityScore: 36 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 14, adjustedPriority: 7.71, adjustedEbitda: 7.71, peNativeScore: 7.95, portfolioAdjustedPriority: 18.51 },
  { rank: 14, name: 'Ascential Technologies', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 500, ebitda: 50, scores: { ebitdaImpact: 7, revenueEnablement: 6, riskReduction: 7, orgCapacity: 6, dataReadiness: 7, techInfrastructure: 6, timelineFit: 7, valueScore: 6.75, readinessScore: 6.45, priorityScore: 33 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 17, adjustedPriority: 6.36, adjustedEbitda: 7.23, peNativeScore: 6.53, portfolioAdjustedPriority: 17.17 },
  { rank: 15, name: 'Pave America', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 500, ebitda: 50, scores: { ebitdaImpact: 7, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 6, timelineFit: 7, valueScore: 6.25, readinessScore: 5.45, priorityScore: 29.25 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 6, replicationCount: 17, adjustedPriority: 5.22, adjustedEbitda: 6.7, peNativeScore: 5.75, portfolioAdjustedPriority: 14.08 },
  { rank: 16, name: 'Singer Industrial', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 500, ebitda: 50, scores: { ebitdaImpact: 7, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 6, timelineFit: 7, valueScore: 6.25, readinessScore: 5.45, priorityScore: 29.25 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 6, replicationCount: 17, adjustedPriority: 5.22, adjustedEbitda: 6.7, peNativeScore: 5.75, portfolioAdjustedPriority: 14.08 },
  { rank: 17, name: 'Nations Roof', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 400, ebitda: 40, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 7, timelineFit: 7, valueScore: 7.25, readinessScore: 6.35, priorityScore: 27.2 }, quadrant: 'Quick Win', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 7, replicationCount: 17, adjustedPriority: 5.63, adjustedEbitda: 6.21, peNativeScore: 6.75, portfolioAdjustedPriority: 15.19 },
  { rank: 18, name: 'ThreeSixty Group', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 500, ebitda: 40, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6.75, readinessScore: 6, priorityScore: 25.5 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 7, replicationCount: 11, adjustedPriority: 4.91, adjustedEbitda: 5.79, peNativeScore: 6.25, portfolioAdjustedPriority: 10.31 },
  { rank: 19, name: "Jack's Family Restaurants", cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 450, ebitda: 36, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 6, timelineFit: 7, valueScore: 6.5, readinessScore: 5.4, priorityScore: 21.42 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 11, adjustedPriority: 3.97, adjustedEbitda: 5.01, peNativeScore: 5.88, portfolioAdjustedPriority: 8.33 },
  { rank: 20, name: 'RED Global', cohort: 'Services', investmentGroup: 'Small Business', revenue: 200, ebitda: 30, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.75, readinessScore: 6, priorityScore: 19.13 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 7, replicationCount: 14, adjustedPriority: 3.68, adjustedEbitda: 4.34, peNativeScore: 6.25, portfolioAdjustedPriority: 8.82 },
  { rank: 21, name: 'Verdesian Life Sciences', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 300, ebitda: 30, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 6, timelineFit: 6, valueScore: 5.75, readinessScore: 5.3, priorityScore: 16.58 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 17, adjustedPriority: 2.74, adjustedEbitda: 3.69, peNativeScore: 5.62, portfolioAdjustedPriority: 7.41 },
  { rank: 22, name: 'Spectrum Control', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 250, ebitda: 25, scores: { ebitdaImpact: 7, revenueEnablement: 6, riskReduction: 7, orgCapacity: 7, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.75, readinessScore: 6.45, priorityScore: 16.5 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 7, replicationCount: 17, adjustedPriority: 3.21, adjustedEbitda: 3.62, peNativeScore: 6.53, portfolioAdjustedPriority: 8.68 },
  { rank: 23, name: 'SCIO Automation', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 8, timelineFit: 7, valueScore: 7.5, readinessScore: 7.15, priorityScore: 14.65 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 17, adjustedPriority: 3.14, adjustedEbitda: 3.21, peNativeScore: 7.28, portfolioAdjustedPriority: 8.48 },
  { rank: 24, name: 'Window Nation', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 250, ebitda: 20, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 5, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.75, readinessScore: 6.1, priorityScore: 12.85 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Revenue Growth', platformClassification: 'Hybrid', replicationPotential: 6, replicationCount: 11, adjustedPriority: 2.48, adjustedEbitda: 2.89, peNativeScore: 6.38, portfolioAdjustedPriority: 5.20 },
  { rank: 25, name: 'The Lifetime Value Co', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 150, ebitda: 22.5, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 7, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 8, timelineFit: 8, valueScore: 7.75, readinessScore: 8, priorityScore: 17.72 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 14, adjustedPriority: 3.92, adjustedEbitda: 3.74, peNativeScore: 7.88, portfolioAdjustedPriority: 9.42 },
  { rank: 26, name: 'ROI CX Solutions', cohort: 'Services', investmentGroup: 'Small Business', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 8, revenueEnablement: 7, riskReduction: 7, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 7, timelineFit: 8, valueScore: 7.5, readinessScore: 7.1, priorityScore: 14.6 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 14, adjustedPriority: 3.12, adjustedEbitda: 3.21, peNativeScore: 7.25, portfolioAdjustedPriority: 7.49 },
  { rank: 27, name: 'Chemical Guys', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 200, ebitda: 16, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 5, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 7, timelineFit: 7, valueScore: 6.75, readinessScore: 7, priorityScore: 11 }, quadrant: 'Quick Win', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 7, replicationCount: 11, adjustedPriority: 2.12, adjustedEbitda: 2.31, peNativeScore: 6.88, portfolioAdjustedPriority: 4.46 },
  { rank: 28, name: 'Hero Digital', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 100, ebitda: 15, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 8, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 8, timelineFit: 8, valueScore: 8, readinessScore: 8, priorityScore: 12 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 14, adjustedPriority: 2.57, adjustedEbitda: 2.57, peNativeScore: 8, portfolioAdjustedPriority: 6.17 },
  { rank: 29, name: 'Bespoke Partners', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 100, ebitda: 15, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 8, dataReadiness: 7, techInfrastructure: 7, timelineFit: 8, valueScore: 7, readinessScore: 7.45, priorityScore: 10.84 }, quadrant: 'Champion', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 14, adjustedPriority: 2.43, adjustedEbitda: 2.25, peNativeScore: 7.18, portfolioAdjustedPriority: 5.84 },
  { rank: 30, name: 'Mark Spain Real Estate', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 100, ebitda: 10, scores: { ebitdaImpact: 8, revenueEnablement: 8, riskReduction: 6, orgCapacity: 8, dataReadiness: 8, techInfrastructure: 7, timelineFit: 8, valueScore: 7.5, readinessScore: 7.85, priorityScore: 7.68 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 14, adjustedPriority: 1.64, adjustedEbitda: 1.61, peNativeScore: 7.65, portfolioAdjustedPriority: 3.93 },
  { rank: 31, name: 'Monroe Engineering', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 6, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 10.85 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 1.78, adjustedEbitda: 2.46, peNativeScore: 5.38, portfolioAdjustedPriority: 4.80 },
  { rank: 32, name: 'TileBar', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 200, ebitda: 16, scores: { ebitdaImpact: 6, revenueEnablement: 7, riskReduction: 5, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6.25, readinessScore: 6, priorityScore: 9.8 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 11, adjustedPriority: 1.75, adjustedEbitda: 2.14, peNativeScore: 6.13, portfolioAdjustedPriority: 3.67 },
  { rank: 33, name: 'Crane Engineering', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 6, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 10.85 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 1.78, adjustedEbitda: 2.46, peNativeScore: 5.38, portfolioAdjustedPriority: 4.80 },
  { rank: 34, name: 'Dana Safety Supply', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 150, ebitda: 15, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.5, readinessScore: 5.1, priorityScore: 7.95 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 1.25, adjustedEbitda: 1.77, peNativeScore: 5.3, portfolioAdjustedPriority: 3.38 },
  { rank: 35, name: 'Barnet Products', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 150, ebitda: 15, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 6, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 8.14 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 1.34, adjustedEbitda: 1.85, peNativeScore: 5.38, portfolioAdjustedPriority: 3.60 },
  { rank: 36, name: 'EZ Texting', cohort: 'Services', investmentGroup: 'Middle Market', revenue: 100, ebitda: 15, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 7, dataReadiness: 8, techInfrastructure: 8, timelineFit: 8, valueScore: 7, readinessScore: 7.6, priorityScore: 10.95 }, quadrant: 'Champion', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 14, adjustedPriority: 2.46, adjustedEbitda: 2.25, peNativeScore: 7.25, portfolioAdjustedPriority: 5.90 },
  { rank: 37, name: 'Unisyn Precision', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 100, ebitda: 10, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 6, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 5.43 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 0.89, adjustedEbitda: 1.23, peNativeScore: 5.38, portfolioAdjustedPriority: 2.40 },
  { rank: 38, name: 'WorldWide Electric', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 100, ebitda: 10, scores: { ebitdaImpact: 6, revenueEnablement: 5, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.5, readinessScore: 5.1, priorityScore: 5.3 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 4, replicationCount: 17, adjustedPriority: 0.84, adjustedEbitda: 1.18, peNativeScore: 5.3, portfolioAdjustedPriority: 2.26 },
  { rank: 39, name: '50 Floor', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 180, ebitda: 14.4, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 5, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.5, readinessScore: 6.05, priorityScore: 9.04 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 11, adjustedPriority: 1.61, adjustedEbitda: 2.01, peNativeScore: 6.23, portfolioAdjustedPriority: 3.37 },
  { rank: 40, name: 'Splash Car Wash', cohort: 'Consumer', investmentGroup: 'Middle Market', revenue: 150, ebitda: 12, scores: { ebitdaImpact: 6, revenueEnablement: 7, riskReduction: 5, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 7, valueScore: 6.25, readinessScore: 6.05, priorityScore: 7.38 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 11, adjustedPriority: 1.32, adjustedEbitda: 1.61, peNativeScore: 6.13, portfolioAdjustedPriority: 2.76 },
  { rank: 41, name: 'Meritus Gas Partners', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 5, revenueEnablement: 5, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 5, valueScore: 5, readinessScore: 5, priorityScore: 10 }, quadrant: 'Foundation', track: 'T3', trackDescription: 'Exit Multiplier Plays', implementationYear: 'Year 3-4', implementationQuarter: 'Q3-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 3, replicationCount: 17, adjustedPriority: 1.43, adjustedEbitda: 2.14, peNativeScore: 5, portfolioAdjustedPriority: 3.86 },
  { rank: 42, name: 'Chemtron RiverBend', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 100, ebitda: 10, scores: { ebitdaImpact: 5, revenueEnablement: 5, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 5, valueScore: 5, readinessScore: 5, priorityScore: 5 }, quadrant: 'Foundation', track: 'T3', trackDescription: 'Exit Multiplier Plays', implementationYear: 'Year 3-4', implementationQuarter: 'Q3-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 3, replicationCount: 17, adjustedPriority: 0.71, adjustedEbitda: 1.07, peNativeScore: 5, portfolioAdjustedPriority: 1.93 },
  { rank: 43, name: 'Cimsense', cohort: 'Industrial', investmentGroup: 'Small Business', revenue: 50, ebitda: 5, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 6, timelineFit: 6, valueScore: 5.75, readinessScore: 5.25, priorityScore: 2.75 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 17, adjustedPriority: 0.45, adjustedEbitda: 0.62, peNativeScore: 5.5, portfolioAdjustedPriority: 1.22 },
  { rank: 44, name: 'Commonwealth Pain', cohort: 'Healthcare', investmentGroup: 'Middle Market', revenue: 200, ebitda: 20, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 7, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6.25, readinessScore: 6, priorityScore: 12.25 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 6, replicationCount: 7, adjustedPriority: 2.19, adjustedEbitda: 2.68, peNativeScore: 6.13, portfolioAdjustedPriority: 3.72 },
  { rank: 45, name: 'Cenegenics', cohort: 'Healthcare', investmentGroup: 'Middle Market', revenue: 100, ebitda: 10, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6, readinessScore: 6, priorityScore: 6 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 7, adjustedPriority: 1.03, adjustedEbitda: 1.29, peNativeScore: 6, portfolioAdjustedPriority: 1.75 },
  { rank: 46, name: 'Impetus Wellness', cohort: 'Healthcare', investmentGroup: 'Small Business', revenue: 48, ebitda: 4.8, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6, readinessScore: 6, priorityScore: 2.88 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 7, adjustedPriority: 0.49, adjustedEbitda: 0.62, peNativeScore: 6, portfolioAdjustedPriority: 0.84 },
  { rank: 47, name: 'AmeriVet Partners', cohort: 'Healthcare', investmentGroup: 'Middle Market', revenue: 0, ebitda: 0, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6, readinessScore: 6, priorityScore: 0 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 7, adjustedPriority: 0, adjustedEbitda: 0, peNativeScore: 6, portfolioAdjustedPriority: 0 },
  { rank: 48, name: 'Montway', cohort: 'Logistics', investmentGroup: 'Middle Market', revenue: 180, ebitda: 18, scores: { ebitdaImpact: 7, revenueEnablement: 7, riskReduction: 6, orgCapacity: 7, dataReadiness: 7, techInfrastructure: 7, timelineFit: 7, valueScore: 6.75, readinessScore: 7, priorityScore: 12.38 }, quadrant: 'Quick Win', track: 'T1', trackDescription: 'EBITDA Accelerators', implementationYear: 'Year 1', implementationQuarter: 'Q1-Q2', valueTheme: 'Margin Expansion', platformClassification: 'Platform', replicationPotential: 8, replicationCount: 5, adjustedPriority: 2.61, adjustedEbitda: 2.60, peNativeScore: 6.88, portfolioAdjustedPriority: 3.92 },
  { rank: 49, name: 'P&B Intermodal', cohort: 'Logistics', investmentGroup: 'Small Business', revenue: 25, ebitda: 2.5, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 1.36 }, quadrant: 'Foundation', track: 'T3', trackDescription: 'Exit Multiplier Plays', implementationYear: 'Year 3-4', implementationQuarter: 'Q3-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 3, replicationCount: 5, adjustedPriority: 0.22, adjustedEbitda: 0.31, peNativeScore: 5.38, portfolioAdjustedPriority: 0.34 },
  { rank: 50, name: 'American Expediting', cohort: 'Logistics', investmentGroup: 'Small Business', revenue: 0, ebitda: 4.08, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 2.22 }, quadrant: 'Foundation', track: 'T3', trackDescription: 'Exit Multiplier Plays', implementationYear: 'Year 3-4', implementationQuarter: 'Q3-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Point', replicationPotential: 3, replicationCount: 5, adjustedPriority: 0.36, adjustedEbitda: 0.50, peNativeScore: 5.38, portfolioAdjustedPriority: 0.55 },
  { rank: 51, name: 'AS Software', cohort: 'Services', investmentGroup: 'Small Business', revenue: 40, ebitda: 8, scores: { ebitdaImpact: 7, revenueEnablement: 8, riskReduction: 6, orgCapacity: 7, dataReadiness: 8, techInfrastructure: 8, timelineFit: 7, valueScore: 7, readinessScore: 7.55, priorityScore: 5.82 }, quadrant: 'Champion', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Revenue Growth', platformClassification: 'Platform', replicationPotential: 9, replicationCount: 14, adjustedPriority: 1.31, adjustedEbitda: 1.2, peNativeScore: 7.23, portfolioAdjustedPriority: 3.14 },
  { rank: 52, name: 'American Dental', cohort: 'Healthcare', investmentGroup: 'Middle Market', revenue: 0, ebitda: 0, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6, readinessScore: 6, priorityScore: 0 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 7, adjustedPriority: 0, adjustedEbitda: 0, peNativeScore: 6, portfolioAdjustedPriority: 0 },
  { rank: 53, name: 'Rees Scientific', cohort: 'Healthcare', investmentGroup: 'Small Business', revenue: 0, ebitda: 0, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 6, orgCapacity: 6, dataReadiness: 6, techInfrastructure: 6, timelineFit: 6, valueScore: 6, readinessScore: 6, priorityScore: 0 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 7, adjustedPriority: 0, adjustedEbitda: 0, peNativeScore: 6, portfolioAdjustedPriority: 0 },
  { rank: 54, name: 'Veseris', cohort: 'Industrial', investmentGroup: 'Middle Market', revenue: 765, ebitda: 76.5, scores: { ebitdaImpact: 6, revenueEnablement: 6, riskReduction: 5, orgCapacity: 5, dataReadiness: 5, techInfrastructure: 5, timelineFit: 6, valueScore: 5.75, readinessScore: 5.1, priorityScore: 41.51 }, quadrant: 'Foundation', track: 'T2', trackDescription: 'Growth Enablers', implementationYear: 'Year 2-3', implementationQuarter: 'Q2-Q4', valueTheme: 'Margin Expansion', platformClassification: 'Hybrid', replicationPotential: 5, replicationCount: 17, adjustedPriority: 6.80, adjustedEbitda: 9.42, peNativeScore: 5.38, portfolioAdjustedPriority: 18.36 },
]

// Calculate totals for quick access
export function getPortfolioTotals() {
  const totals = {
    totalCompanies: PORTFOLIO_DATA.length,
    totalRevenue: 0,
    totalEbitda: 0,
    totalEbitdaOpportunity: 0,
    champions: 0,
    quickWins: 0,
    strategic: 0,
    foundations: 0,
    t1Count: 0,
    t2Count: 0,
    t3Count: 0,
  }

  for (const company of PORTFOLIO_DATA) {
    totals.totalRevenue += company.revenue
    totals.totalEbitda += company.ebitda
    totals.totalEbitdaOpportunity += company.adjustedEbitda

    if (company.quadrant === 'Champion') totals.champions++
    else if (company.quadrant === 'Quick Win') totals.quickWins++
    else if (company.quadrant === 'Strategic') totals.strategic++
    else totals.foundations++

    if (company.track === 'T1') totals.t1Count++
    else if (company.track === 'T2') totals.t2Count++
    else totals.t3Count++
  }

  return totals
}

// Pre-computed summaries for dashboard
export const COHORT_SUMMARY = {
  Industrial: {
    count: PORTFOLIO_DATA.filter(c => c.cohort === 'Industrial').length,
    totalRevenue: PORTFOLIO_DATA.filter(c => c.cohort === 'Industrial').reduce((sum, c) => sum + c.revenue, 0),
    totalEbitda: PORTFOLIO_DATA.filter(c => c.cohort === 'Industrial').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.cohort === 'Industrial').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Services: {
    count: PORTFOLIO_DATA.filter(c => c.cohort === 'Services').length,
    totalRevenue: PORTFOLIO_DATA.filter(c => c.cohort === 'Services').reduce((sum, c) => sum + c.revenue, 0),
    totalEbitda: PORTFOLIO_DATA.filter(c => c.cohort === 'Services').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.cohort === 'Services').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Consumer: {
    count: PORTFOLIO_DATA.filter(c => c.cohort === 'Consumer').length,
    totalRevenue: PORTFOLIO_DATA.filter(c => c.cohort === 'Consumer').reduce((sum, c) => sum + c.revenue, 0),
    totalEbitda: PORTFOLIO_DATA.filter(c => c.cohort === 'Consumer').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.cohort === 'Consumer').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Healthcare: {
    count: PORTFOLIO_DATA.filter(c => c.cohort === 'Healthcare').length,
    totalRevenue: PORTFOLIO_DATA.filter(c => c.cohort === 'Healthcare').reduce((sum, c) => sum + c.revenue, 0),
    totalEbitda: PORTFOLIO_DATA.filter(c => c.cohort === 'Healthcare').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.cohort === 'Healthcare').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Logistics: {
    count: PORTFOLIO_DATA.filter(c => c.cohort === 'Logistics').length,
    totalRevenue: PORTFOLIO_DATA.filter(c => c.cohort === 'Logistics').reduce((sum, c) => sum + c.revenue, 0),
    totalEbitda: PORTFOLIO_DATA.filter(c => c.cohort === 'Logistics').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.cohort === 'Logistics').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
}

export const QUADRANT_SUMMARY = {
  Champion: {
    count: PORTFOLIO_DATA.filter(c => c.quadrant === 'Champion').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.quadrant === 'Champion').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.quadrant === 'Champion').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  'Quick Win': {
    count: PORTFOLIO_DATA.filter(c => c.quadrant === 'Quick Win').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.quadrant === 'Quick Win').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.quadrant === 'Quick Win').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Strategic: {
    count: PORTFOLIO_DATA.filter(c => c.quadrant === 'Strategic').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.quadrant === 'Strategic').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.quadrant === 'Strategic').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
  Foundation: {
    count: PORTFOLIO_DATA.filter(c => c.quadrant === 'Foundation').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.quadrant === 'Foundation').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.quadrant === 'Foundation').reduce((sum, c) => sum + c.adjustedEbitda, 0),
  },
}

export const TRACK_SUMMARY = {
  T1: {
    name: 'EBITDA Accelerators',
    count: PORTFOLIO_DATA.filter(c => c.track === 'T1').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.track === 'T1').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.track === 'T1').reduce((sum, c) => sum + c.adjustedEbitda, 0),
    timeline: '0-12 months',
    allocation: '40-50%',
  },
  T2: {
    name: 'Growth Enablers',
    count: PORTFOLIO_DATA.filter(c => c.track === 'T2').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.track === 'T2').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.track === 'T2').reduce((sum, c) => sum + c.adjustedEbitda, 0),
    timeline: '6-24 months',
    allocation: '30-40%',
  },
  T3: {
    name: 'Exit Multiplier Plays',
    count: PORTFOLIO_DATA.filter(c => c.track === 'T3').length,
    totalEbitda: PORTFOLIO_DATA.filter(c => c.track === 'T3').reduce((sum, c) => sum + c.ebitda, 0),
    totalOpportunity: PORTFOLIO_DATA.filter(c => c.track === 'T3').reduce((sum, c) => sum + c.adjustedEbitda, 0),
    timeline: '12-36 months',
    allocation: '15-25%',
  },
}
